### ISSUE TITLE
isNone function in tests is not valid function

### ISSUE THREAD

**Issue by jon49** [fantasyland/fantasy-options#6]
https://github.com/fantasyland/fantasy-options/blob/master/test/option.js#L42

Not an issue with the actual library. `isNone` is never actually used in the testing either, just defined. If someone stumbles upon it and uses it in their code it will just lead to confusion. In `daggy.js` `taggedSum`s doesn't actually create a `constructor` for keys with values of zero length.

Here's my implementation of `isNone`:

```javascript
var isNone = function(o){
   return isOption(o) && not(isSome(o))
}
```

I was using `bilby.js` before so this confused me a little.

**Comment by SimonRichardson** [comment]
Sorry for this late response, I'm just finding this out as well :D

Fixed in the latest version. https://github.com/fantasyland/fantasy-options/commit/416627e19943bf5bbd3f0c1f77dd63364718daad
